name = "cf-kv"
type = "javascript"

account_id = "47a542dd0351aad13c77c43c81866412"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-01"
kv_namespaces = [
         { binding = "demo_kv", id = "dc485a9feac8460c8add2fd8300bc214" }
]